package SQLForEXEL;

public class SQLforExelCloseInkasYes {
    
    public String SqlCount(){
        return "select substr(ATMLUNO,6,9) atm, NTAREST1, NTAREST2, NTAREST3, NTAREST4,NTADIVERT1, NTADIVERT2, NTADIVERT3, NTADIVERT4, NTAFORG1, NTAFORG2, NTAFORG3, NTAFORG4,\n" +
                " ((NTAREST1*(NTANOM1/100)) + (NTAREST2*(NTANOM2/100))+(NTAREST3*(NTANOM3/100))+(NTAREST4*(NTANOM4/100))+((NTADIVERT1 + NTAFORG1)*(NTANOM1/100))+((NTADIVERT2 + NTAFORG2)*(NTANOM2/100))+((NTADIVERT3 + NTAFORG3)*(NTANOM3/100))+((NTADIVERT4 + NTAFORG4)*(NTANOM4/100))) tec\n" +
                "from RONINKAS, rondo \n" +
                "where DTSTARTEND between to_date(trunc(sysdate)-1,'DD.MM.RRRR HH24:MI:SS') and to_date(trunc(sysdate),'DD.MM.RRRR HH24:MI:SS')  and RONLINK = SNUM \n" +
                "and ((NTAREST1 + NTAREST2)+(NTAREST3+NTAREST4)+(NTADIVERT1 + NTAFORG1)+(NTADIVERT2 + NTAFORG2)+(NTADIVERT3 + NTAFORG3)+(NTADIVERT4 + NTAFORG4)) > 0 and TYPEBEG in (0,1)\n" +
                "group by substr(ATMLUNO,6,9), NTAREST1, NTAREST2, NTAREST3, NTAREST4,NTADIVERT1, NTAFORG1, NTADIVERT2,NTAFORG2, NTADIVERT3, NTAFORG3, NTADIVERT4, NTAFORG4,\n" +
                "((NTAREST1*(NTANOM1/100)) + (NTAREST2*(NTANOM2/100))+(NTAREST3*(NTANOM3/100))+(NTAREST4*(NTANOM4/100))+((NTADIVERT1 + NTAFORG1)*(NTANOM1/100))+((NTADIVERT2 + NTAFORG2)*(NTANOM2/100))+((NTADIVERT3 + NTAFORG3)*(NTANOM3/100))+((NTADIVERT4 + NTAFORG4)*(NTANOM4/100)))\n" +
                "order by substr(ATMLUNO,6,9) ASC";
    }    
}
